"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {products,Product} from "@/lib/products";
type CartItem={slug:string;plan?:string};
const key="dpb-cart";
export function useCart(){const [cart,setCart]=useState<CartItem[]>([]);useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem(key)||"[]"))}catch{}},[]);const save=(next:CartItem[])=>{setCart(next);localStorage.setItem(key,JSON.stringify(next));window.dispatchEvent(new Event("cart-change"))};return {cart,add:(item:CartItem)=>save([...cart,item]),remove:(i:number)=>save(cart.filter((_,n)=>n!==i)),clear:()=>save([])}}
export function AddToCart({slug,plan="Standard"}:{slug:string;plan?:string}){const [added,setAdded]=useState(false);const cart=useCart();return <button className="button buttonDark" onClick={()=>{cart.add({slug,plan});setAdded(true);setTimeout(()=>setAdded(false),1400)}}>{added?"Added to cart":"Add to cart"} <span>↗</span></button>}
export function BuyNow({slug,plan="Standard"}:{slug:string;plan?:string}){return <Link className="button buttonDark" href={"/checkout?product="+encodeURIComponent(slug)+"&plan="+encodeURIComponent(plan)}>Buy now <span>↗</span></Link>}
export function CartButton(){const [count,setCount]=useState(0);useEffect(()=>{const update=()=>{try{setCount(JSON.parse(localStorage.getItem(key)||"[]").length)}catch{}};update();window.addEventListener("cart-change",update);return()=>window.removeEventListener("cart-change",update)},[]);return <Link className="cartButton" href="/cart">Cart {count>0&&<b>{count}</b>}</Link>}
export function Header(){return <header className="siteHeader"><div className="headerInner"><Link className="brandLogo" href="/" aria-label="Digital Products Bundle home"><img src="/logo.svg" alt="Digital Products Bundle"/></Link><nav><Link href="/products">Shop</Link><Link href="/products#categories">Categories</Link><Link href="/products#bundles">Bundles</Link><Link href="/faq">Help</Link></nav><div className="headerRight"><Link className="searchLink" href="/products">Search <span>⌕</span></Link><CartButton/></div></div></header>}
export function TrustStrip(){return <div className="trustStrip"><div><span className="statusDot"/>Secure payment</div><div>Digital delivery</div><div>Clear product details</div><div>Support available</div></div>}
export function ProductCard({product,index=0}:{product:Product;index?:number}){return <article className={"productCard editorialCard card"+index}><Link href={"/products/"+product.slug} className="productVisual"><div className="visualMeta"><span>0{index+1}</span><span>{product.badge||"DIGITAL"}</span></div><div className="visualIdentity"><small>{product.type}</small><strong>{product.imageLabel}</strong><span>{product.category}</span></div><div className="visualBottom"><span>Digital Products Bundle</span><span>↗</span></div></Link><div className="productCardBody"><div><div className="productCategory">{product.category}</div><Link href={"/products/"+product.slug} className="productName">{product.name}</Link></div><div className="cardBottom"><span>{product.pricing?.[0]?.note||"Digital product"}</span><strong>{product.pricing?.[0]?.price||"View"}</strong></div></div></article>}
export function SiteFooter(){return <footer className="siteFooter"><div className="footerTop"><div><Link className="brandLogo footerBrandLogo" href="/" aria-label="Digital Products Bundle home"><img src="/logo.svg" alt="Digital Products Bundle"/></Link><p>Practical digital products, tools and resources for people who want to work with less friction.</p></div><div><span className="footerLabel">Explore</span><Link href="/products">All products</Link><Link href="/products#categories">Categories</Link><Link href="/products#bundles">Bundles</Link></div><div><span className="footerLabel">Help</span><Link href="/faq">FAQs</Link><Link href="/contact">Contact</Link><Link href="/refund-policy">Refund policy</Link></div><div><span className="footerLabel">Company</span><Link href="/about">About</Link><Link href="/blog">Resources</Link><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link></div></div><div className="footerMaintained"><div><span className="footerLabel">Maintained by</span><strong>R.K Digital Media</strong><a href="tel:+919871530594">+91 98715 30594</a></div><div><span className="footerLabel">Follow</span><a href="https://www.instagram.com/digital_products_bundle/" target="_blank" rel="noopener noreferrer">Instagram @digital_products_bundle ↗</a></div><div><span className="footerLabel">Sponsored link</span><a href="https://rkdigitalmedia.in/" target="_blank" rel="sponsored nofollow noopener noreferrer">R.K Digital Media ↗</a></div></div><div className="footerBottom"><span>© 2026 Digital Products Bundle</span><span>Maintained by R.K Digital Media · Built for digital delivery.</span></div></footer>}
