"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {products,Product} from "@/lib/products";
type CartItem={slug:string;plan?:string};
const key="dpb-cart";
export function useCart(){const [cart,setCart]=useState<CartItem[]>([]);useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem(key)||"[]"))}catch{}},[]);const save=(next:CartItem[])=>{setCart(next);localStorage.setItem(key,JSON.stringify(next));window.dispatchEvent(new Event("cart-change"))};return {cart,add:(item:CartItem)=>save([...cart,item]),remove:(i:number)=>save(cart.filter((_,n)=>n!==i)),clear:()=>save([])}}
export function AddToCart({slug,plan="Standard"}:{slug:string;plan?:string}){const [added,setAdded]=useState(false);const cart=useCart();return <button className="button buttonDark" onClick={()=>{cart.add({slug,plan});setAdded(true);setTimeout(()=>setAdded(false),1400)}}>{added?"Added to cart":"Add to cart"} <span>→</span></button>}
export function BuyNow({slug,plan="Standard"}:{slug:string;plan?:string}){return <Link className="button buttonDark" href={"/checkout?product="+encodeURIComponent(slug)+"&plan="+encodeURIComponent(plan)}>Buy now <span>→</span></Link>}
export function CartButton(){const [count,setCount]=useState(0);useEffect(()=>{const update=()=>{try{setCount(JSON.parse(localStorage.getItem(key)||"[]").length)}catch{}};update();window.addEventListener("cart-change",update);return()=>window.removeEventListener("cart-change",update)},[]);return <Link className="cartButton" href="/cart">Cart {count>0&&<b>{count}</b>}</Link>}
export function Header(){return <header className="siteHeader"><div className="headerInner"><Link className="logo" href="/"><span className="logoMark">DP</span><span>Digital Products Bundle</span></Link><nav><Link href="/products">Shop</Link><Link href="/products#categories">Categories</Link><Link href="/products#bundles">Bundles</Link><Link href="/faq">Help</Link></nav><div className="headerRight"><Link className="searchLink" href="/products">Search</Link><CartButton/></div></div></header>}
export function TrustStrip(){return <div className="trustStrip"><span><b>✓</b> Secure checkout</span><span><b>✓</b> Digital delivery</span><span><b>✓</b> Clear product details</span><span><b>✓</b> Support available</span></div>}
export function ProductCard({product}:{product:Product}){return <article className="productCard"><Link href={"/products/"+product.slug} className="productVisual"><span className="productBadge">{product.badge||"Digital"}</span><div className="visualTop">{product.type}</div><div className="visualName">{product.imageLabel}</div><div className="visualBottom">DIGITAL PRODUCTS BUNDLE</div></Link><div className="productCardBody"><div className="productCategory">{product.category}</div><Link href={"/products/"+product.slug} className="productName">{product.name}</Link><p>{product.shortDescription}</p><div className="cardBottom"><strong>{product.pricing?.[0]?.price||"View details"}</strong><Link href={"/products/"+product.slug}>View product</Link></div></div></article>}
export function SiteFooter(){return <footer className="siteFooter"><div className="footerGrid"><div><Link className="logo footerLogo" href="/"><span className="logoMark">DP</span><span>Digital Products Bundle</span></Link><p>Practical digital products, tools and resources for businesses, creators and freelancers.</p></div><div><h4>Shop</h4><Link href="/products">All products</Link><Link href="/products#categories">Categories</Link><Link href="/products#bundles">Bundles</Link></div><div><h4>Help</h4><Link href="/faq">FAQs</Link><Link href="/contact">Contact</Link><Link href="/refund-policy">Refund policy</Link></div><div><h4>Company</h4><Link href="/about">About</Link><Link href="/blog">Resources</Link><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link></div></div><div className="footerBottom"><span>© 2026 Digital Products Bundle</span><span>Secure online payments · Digital delivery</span></div></footer>}
